[package]
name = "slugify"
version = "0.0.1"
edition = "2024"
autoexamples = false
autobenches = false
default-run = "slugify-filenames"

[lib]
name = "slugify"
path = "slugify/lib.rs"
# crate-type = ["dylib"]

doctest = false
bench = false


[[bin]]
name = "slugify-filenames"
path = "slugify-filenames.rs"
doctest = false
bench = false
doc = false

[[bin]]
name = "slugify-string"
path = "slugify-string.rs"
doctest = false
bench = false
doc = false

[dependencies]
clap = { version = "4.5.40", features = ["derive", "env", "string", "unicode", "wrap_help"] }
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
iocore = { version = "3.1.0" }
strip-ansi-escapes = "0.2.1"
sanitation = "1.0.3"

[dev-dependencies]
iocore-test = { version = "3.1.0" }
